### ISSUE TITLE
[1.11.2] Crash

### ISSUE THREAD

**Issue by ghost** [MatrexsVigil/harvestcraft#12]
### Steps to reproduce:

1. Within a chunk place Known Thermal Expension Blocks and Known HarvestCraft Blocks
2. Unload Chunk (Exit world or go do something in another chuck for a while)
3. Reload world or come back to chunk with placed blocks

### Known Affected Mod Blocks

- Pressure (Pam's)
- Redstone Furnace (TE)
- Water Trap (Pam's)
- Magma Crucible (TE)
- Market (Pam's)
- Energetic Infuser (TE)

____
### Affected Versions

- Minecraft 1.11.2
  - forge-13.20.1.2429
  - Pam's HarvestCraft 1.11.2h
  - ThermalExpansion-1.11.2-5.2.6.22-universal
  - Other mods
    - CodeChickenLib-1.11.2-3.0.0.284-universal
    - CoFHCore-1.11.2-4.2.7.15-universal
    - jei_1.11.2-4.5.0.295
    - ThermalDynamics-1.11.2-2.2.6.13-universal
    - ThermalFoundation-1.11.2-2.2.5.16-universal

### Crash report 

- Pressure (Pam's) and Redstone Furnace (TE)
  - https://pastebin.com/raw/1eMfbt5t

- Water Trap (Pam's) and Magma Crucible (TE)
  - https://pastebin.com/raw/MYQJd1Wb

- Market (Pam's) and Energetic Infuser (TE)
  - https://pastebin.com/raw/KRHwDbtG

**Comment by Morpheus1101** [comment]
I basically just got this exact thing in 1.12 https://puu.sh/x0t65/7919408438.txt

**Comment by OrdinatorStouff** [comment]
when I went to edit the region file for @Morpheus1101 to log-in without crashing, I noticed the block was saved as "minecraft:pammarket" but thought that it was weird that it wasn't something more like "harvestcraft:market"

I don't know if this is intended or not but wanted to share in case it helps 
![unknown 1](https://user-images.githubusercontent.com/6283913/28947673-fb8c6c26-7865-11e7-91fa-41cfe87b6470.png)

**Comment by PearlCanopus** [comment]
Same here.
You may save your world in a chunk with i.e. Presser and a TE Redstone Furnace built.
Reloading savegame will cause the game to crash, while nothing in my crash-log shows any fault dependency to Harvestcraft. But I tested to remove and readd several mods for days. 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.6.jar)
  NEICorePlugin (NotEnoughItems-1.11.2-2.3.0.227-universal.jar)
  FarseekCoreMod (Farseek-1.11-2.1.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.4.6.1.jar)
  IvToolkit (IvToolkit-1.3.3.jar)
  MalisisSwitchesPlugin (malisisswitches-1.11.2-4.1.0.jar)
  MalisisCorePlugin (malisiscore-1.11.2-5.2.4.jar)
  AppleCore (AppleCore-mc1.11.2-2.2.2.jar)
  CoFH Loading Plugin (CoFHCore-1.11.2-4.2.7.15-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-3.0.0.284-universal.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 8/6/17 3:48 PM
Description: Batching chunks

java.lang.NullPointerException: Batching chunks
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:94)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:60)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:296)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Thread.java:745)


Chunk rendering returns strange results, like turned Storage Drawers or Bibliocraft racks, removed covers/texture from TD, framed drawers or unlinked fluxducts from TD, invisible chests (reappering when running in) and so on.
I checked CoFH for this error and got the hint, that Harvestcraft may cause that.

I removed all CoFH mods and ChickenLib-Mods recebtly. The problem persists.
So I finally removed Harvestcraft from the modlist and the savegame could be loaded without any problems while loaded CoFH and CCL mods again.

**Comment by ghost** [comment]
I am experiencing the same issues as above. A member of my server started reporting strange issues like @PearlCanopus seemed too mention, and eventually after reloading chunks in his houses general area the client crashes.

```
[05:10:00] [main/INFO]: Setting user: TheMakoto
[05:10:04] [main/WARN]: Skipping bad option: lastServer:
[05:10:04] [main/INFO]: LWJGL Version: 2.9.4
[05:10:10] [main/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:mercurius_updater, FMLFileResourcePack:BiblioCraft, FMLFileResourcePack:Chameleon, FMLFileResourcePack:Chisels & Bits, FMLFileResourcePack:CodeChicken Lib, FMLFileResourcePack:CoFH Core, FMLFileResourcePack:CoFH World, FMLFileResourcePack:Dynmap, FMLFileResourcePack:Extra Utilities 2, FMLFileResourcePack:Fairy Lights, FMLFileResourcePack:FTBLib, FMLFileResourcePack:FTBUtilities, FMLFileResourcePack:Inventory Tweaks, FMLFileResourcePack:Iron Chest, FMLFileResourcePack:Just Enough Items, FMLFileResourcePack:JourneyMap, FMLFileResourcePack:Mantle, FMLFileResourcePack:Morpheus, FMLFileResourcePack:Pam's HarvestCraft, FMLFileResourcePack:Redstone Flux, FMLFileResourcePack:Storage Drawers, FMLFileResourcePack:Tails, FMLFileResourcePack:Tinkers' Construct, FMLFileResourcePack:Thermal Expansion, FMLFileResourcePack:Thermal Foundation, FMLFileResourcePack:Thump, John Smith Legacy 1.12.0 v2.zip
[05:10:16] [main/WARN]: File tconstruct:sounds/woodhit1.ogg does not exist, cannot add it to event tconstruct:wood_hit
[05:10:16] [main/WARN]: File tconstruct:sounds/woodhit2.ogg does not exist, cannot add it to event tconstruct:wood_hit
[05:10:16] [main/WARN]: File tconstruct:sounds/woodhit3.ogg does not exist, cannot add it to event tconstruct:wood_hit
[05:10:16] [main/WARN]: File tconstruct:sounds/woodhit4.ogg does not exist, cannot add it to event tconstruct:wood_hit
[05:10:16] [main/WARN]: File tconstruct:sounds/woodhit5.ogg does not exist, cannot add it to event tconstruct:wood_hit
[05:10:16] [main/WARN]: File tconstruct:sounds/stonehit1.ogg does not exist, cannot add it to event tconstruct:stone_hit
[05:10:16] [main/WARN]: File tconstruct:sounds/stonehit2.ogg does not exist, cannot add it to event tconstruct:stone_hit
[05:10:16] [main/WARN]: File tconstruct:sounds/stonehit3.ogg does not exist, cannot add it to event tconstruct:stone_hit
[05:10:16] [main/WARN]: File tconstruct:sounds/crossbowreload.ogg does not exist, cannot add it to event tconstruct:crossbow_reload
[05:10:16] [Sound Library Loader/INFO]: Starting up SoundSystem...
[05:10:16] [Thread-8/INFO]: Initializing LWJGL OpenAL
[05:10:16] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[05:10:16] [Thread-8/INFO]: OpenAL initialized.
[05:10:16] [Sound Library Loader/INFO]: Sound engine started
[05:10:25] [main/INFO]: Created: 8192x4096 textures-atlas
[05:10:26] [main/WARN]: Unable to resolve texture due to upward reference: #bottom in minecraft:models/block/orientable.json
[05:10:26] [main/WARN]: Unable to resolve texture due to upward reference: #bottom in minecraft:models/block/orientable.json
[05:10:26] [main/WARN]: Unable to resolve texture due to upward reference: #bottom in minecraft:models/block/orientable.json
[05:10:26] [main/WARN]: Unable to resolve texture due to upward reference: #bottom in minecraft:models/block/orientable.json
[05:10:27] [main/WARN]: Unable to resolve texture due to upward reference: #bottom in minecraft:models/block/orientable.json
[05:10:27] [main/WARN]: Unable to resolve texture due to upward reference: #bottom in minecraft:models/block/orientable.json
[05:10:27] [main/WARN]: Unable to resolve texture due to upward reference: #bottom in minecraft:models/block/orientable.json
[05:10:27] [main/WARN]: Unable to resolve texture due to upward reference: #bottom in minecraft:models/block/orientable.json
[05:10:27] [main/WARN]: Unable to resolve texture due to upward reference: #bottom in minecraft:models/block/orientable.json
[05:10:27] [main/WARN]: Unable to resolve texture due to upward reference: #bottom in minecraft:models/block/orientable.json
[05:10:27] [main/WARN]: Unable to resolve texture due to upward reference: #bottom in minecraft:models/block/orientable.json
[05:10:27] [main/WARN]: Unable to resolve texture due to upward reference: #bottom in minecraft:models/block/orientable.json
[05:10:27] [main/WARN]: Unable to resolve texture due to upward reference: #bottom in minecraft:models/block/orientable.json
[05:10:28] [main/WARN]: Unable to resolve texture due to upward reference: #bottom in minecraft:models/block/orientable.json
[05:10:28] [main/WARN]: Unable to resolve texture due to upward reference: #bottom in minecraft:models/block/orientable.json
[05:10:28] [main/WARN]: Unable to resolve texture due to upward reference: #bottom in minecraft:models/block/orientable.json
[05:10:28] [main/WARN]: Unable to resolve texture due to upward reference: #bottom in minecraft:models/block/orientable.json
[05:10:28] [main/WARN]: Unable to resolve texture due to upward reference: #bottom in minecraft:models/block/orientable.json
[05:10:28] [main/WARN]: Unable to resolve texture due to upward reference: #bottom in minecraft:models/block/orientable.json
[05:10:28] [main/WARN]: Unable to resolve texture due to upward reference: #bottom in minecraft:models/block/orientable.json
[05:10:28] [main/WARN]: Unable to resolve texture due to upward reference: #bottom in minecraft:models/block/orientable.json
[05:10:28] [main/WARN]: Unable to resolve texture due to upward reference: #bottom in minecraft:models/block/orientable.json
[05:10:28] [main/WARN]: Unable to resolve texture due to upward reference: #bottom in minecraft:models/block/orientable.json
[05:10:32] [main/WARN]: PriceRange(-4, -8) invalid, -8 smaller than -4
[05:10:37] [main/WARN]: Skipping bad option: lastServer:
[05:10:37] [main/INFO]: Narrator library for x64 successfully loaded
[05:10:51] [Server thread/INFO]: Starting integrated minecraft server version 1.12
[05:10:51] [Server thread/INFO]: Generating keypair
[05:10:53] [Server thread/INFO]: Loaded 488 advancements
[05:10:53] [Server thread/INFO]: Preparing start region for level 0
[05:10:54] [Server thread/INFO]: Preparing spawn area: 16%
[05:10:55] [Server thread/WARN]: Keeping entity minecraft:cow that already exists with UUID aab3db9f-da8d-4a34-a2a1-4c98d3fbf1db
[05:10:57] [Server thread/INFO]: Changing view distance to 9, from 10
[05:10:58] [Server thread/INFO]: TheMakoto[local:E:46ffe833] logged in with entity id 314 at (1152.641331392237, 98.82184182309686, 292.97201733190855)
[05:10:58] [Server thread/INFO]: TheMakoto joined the game
[05:10:58] [Server thread/WARN]: Keeping entity minecraft:skeleton that already exists with UUID ef4f0917-2861-43ba-a1cd-bfb4f8829276
[05:10:58] [Server thread/WARN]: Keeping entity minecraft:bat that already exists with UUID 0a364379-dde7-485f-843b-56b7ff5c9b19
[05:10:58] [Server thread/WARN]: Keeping entity minecraft:bat that already exists with UUID cd44401b-2c76-4995-a7a1-feb2b72d74b0
[05:10:58] [Server thread/WARN]: Keeping entity minecraft:cow that already exists with UUID cb7206bd-51d1-4eb0-8acc-ea1db866f40d
[05:10:58] [main/INFO]: [CHAT] A new §eOptiFine§f version is available: §eHD Ultra C5§f
[05:10:58] [Server thread/WARN]: Keeping entity minecraft:sheep that already exists with UUID 03b4f9eb-8de2-465d-995d-7379f6f451dc
[05:10:58] [Server thread/WARN]: Keeping entity minecraft:sheep that already exists with UUID 84214328-80bb-426a-b888-7ed95d8120da
[05:10:58] [Server thread/INFO]: Saving and pausing game...
[05:10:58] [Server thread/INFO]: Saving chunks for level 'OmoCraft'/overworld
[05:10:59] [Server thread/INFO]: Saving chunks for level 'OmoCraft'/the_nether
[05:10:59] [Server thread/INFO]: Saving chunks for level 'OmoCraft'/the_end
[05:10:59] [Server thread/INFO]: Saving chunks for level 'OmoCraft'/Deep Dark
[05:10:59] [Server thread/INFO]: Saving chunks for level 'OmoCraft'/ExtraUtils2_Quarry_Dim
[05:11:00] [main/INFO]: Loaded 375 advancements
[05:11:01] [main/INFO]: [CHAT] §eJourneyMap:§f Press [§bJ§f]
[05:11:01] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bhz.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bhz.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraftforge.items.ItemStackHandler.deserializeNBT(ItemStackHandler.java:192) ~[ItemStackHandler.class:?]
	at com.pam.harvestcraft.tileentities.TileEntityPresser.func_145839_a(TileEntityPresser.java:42) ~[TileEntityPresser.class:?]
	at net.minecraft.tileentity.TileEntity.handleUpdateTag(TileEntity.java:331) ~[avh.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147263_a(NetHandlerPlayClient.java:758) ~[brx.class:?]
	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:96) ~[je.class:?]
	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:18) ~[je.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
[05:11:07] [Client Shutdown Thread/INFO]: Stopping server
```

Also using TE and Harvestcraft. I believe he has a redstone furnace somewhere but I'll have to get some more information from him to be sure, if this isn't helpful enough.

After deleting his Apiary and Presser in MCEdit, I'm able to load the map again.

**Comment by Morpheus1101** [comment]
At this point using any machine from PHC is likely to cause issues at this stage, untill pam releases an updated version.

**Comment by ghost** [comment]
Just wanted to note this issue is still present in 1.12.1b, at least for water traps.

**Comment by Flyrija** [comment]
Had to remove Harvestcraft 1.11.2 because of this. Running a Harvestcraft trap in the same chunk with a Thermal Expansion machine crashes the world and I have to remove Harvestcraft to get the world to load again without crashing instantly.

**Comment by Morpheus1101** [comment]
At this stage the only solution is to remove Harvestcraft untill such time as the issue gets fixed

**Comment by MatrexsVigil** [comment]
Not accepting non 1.12.2 bug reports at this time.

**Comment by bothie** [comment]
Why are you closing this bug? FujiMakoto already told you, that the bug still exists on 1.12.1b, do you really believe the bug to magically disappear between 1.12.1b and 1.12.2?

Anyway, I can also confirm this bug on 1.12.2:

```
Time: 8/5/18 9:21 AM
Description: Batching chunks

java.lang.NullPointerException: Batching chunks
        at codechicken.lib.render.block.CCBlockRendererDispatcher.handleCaughtException(CCBlockRendererDispatcher.java:103)
        at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:85)
        at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200)
        at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
        at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
        at java.lang.Thread.run(Thread.java:748)
```
[crash-2018-08-05_09.21.16-client.txt](https://github.com/MatrexsVigil/harvestcraft/files/2260385/crash-2018-08-05_09.21.16-client.txt)
