### ISSUE TITLE
villager entity server crash

### ISSUE THREAD

**Issue by Sang-bin** [MatrexsVigil/harvestcraft#133]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (AppleCore-mc1.12.2-3.1.0.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.8.4.jar)
  LoadingPlugin (Quark-r1.4-121.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-76-core.jar)
  GottaGoFastLoader (gottagofast-1.0.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.12.2-0.8.3-Anarchy.jar)
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  SHLoadingPlugin (ScalingHealth-1.12-1.3.5-82.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.5.jar)
  TransformerLoader (OpenComputers-MC1.12.1-1.7.1.43.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 1/23/18 3:09 AM
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} as it does not exist in BlockStateContainer{block=harvestcraft:pamcauliflowercrop, properties=[age]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at iguanaman.hungeroverhaul.module.event.HungerOverhaulEventHook.onBlockHarvested(HungerOverhaulEventHook.java:612)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1167_HungerOverhaulEventHook_onBlockHarvested_HarvestDropsEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:277)
	at com.pam.harvestcraft.blocks.growables.BlockPamCrop.func_180653_a(BlockPamCrop.java:188)
	at net.minecraft.block.Block.func_176226_b(Block.java:564)
	at net.minecraft.world.World.func_175655_b(World.java:415)
	at net.minecraft.entity.ai.EntityAIHarvestFarmland.func_75246_d(SourceFile:67)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at iguanaman.hungeroverhaul.module.event.HungerOverhaulEventHook.onBlockHarvested(HungerOverhaulEventHook.java:612)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1167_HungerOverhaulEventHook_onBlockHarvested_HarvestDropsEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:277)
	at com.pam.harvestcraft.blocks.growables.BlockPamCrop.func_180653_a(BlockPamCrop.java:188)
	at net.minecraft.block.Block.func_176226_b(Block.java:564)
	at net.minecraft.world.World.func_175655_b(World.java:415)
	at net.minecraft.entity.ai.EntityAIHarvestFarmland.func_75246_d(SourceFile:67)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: minecraft:villager (net.minecraft.entity.passive.EntityVillager)
	Entity ID: 6990
	Entity Name: Villager
	Entity's Exact location: 754.56, 69.00, -925.70
	Entity's Block location: World: (754,69,-926), Chunk: (at 2,4,2 in 47,-58; contains blocks 752,0,-928 to 767,255,-913), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
	Entity's Momentum: -0.05, -0.08, -0.07
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['Kudryavka'/6844, l='world', x=796.15, y=71.00, z=-944.19]]
	Chunk stats: ServerChunkCache: 610 Drop: 0
	Level seed: 2530148962055893652
	Level generator: ID 07 - quark_realistic, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (24,64,232), Chunk: (at 8,4,8 in 1,14; contains blocks 16,0,224 to 31,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 29081049 game time, 35599933 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 132357 (now: false), thunder time: 61695 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

**Comment by MatrexsVigil** [comment]
This is an issue with Hunter Overhaul, not my mods.
