### ISSUE TITLE
Multiple errors with recipes

### ISSUE THREAD

**Issue by X00LA** [MatrexsVigil/harvestcraft#147]
Hi, got thet errors when starting my server. Looks like that som recipes are broken.

`[Server thread/ERROR]: Parsing error loading built-in advancement minecraft:recipes/food/pumpkin_pie
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:pumpkin_pie'
        at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
        at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
        at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
        at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:203) ~[i$a.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
        at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
        at net.minecraft.advancements.AdvancementManager.func_192777_a(AdvancementManager.java:184) [ns.class:?]
        at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:68) [ns.class:?]
        at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
        at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
[15:13:52] [Server thread/ERROR]: Parsing error loading built-in advancement minecraft:recipes/food/mushroom_stew
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:mushroom_stew'
        at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
        at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
        at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
        at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:203) ~[i$a.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
        at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
        at net.minecraft.advancements.AdvancementManager.func_192777_a(AdvancementManager.java:184) [ns.class:?]
        at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:68) [ns.class:?]
        at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
        at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
[15:13:52] [Server thread/ERROR]: Parsing error loading built-in advancement minecraft:recipes/food/cookie
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:cookie'
        at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
        at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
        at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
        at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:203) ~[i$a.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
        at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
        at net.minecraft.advancements.AdvancementManager.func_192777_a(AdvancementManager.java:184) [ns.class:?]
        at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:68) [ns.class:?]
        at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
        at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
[15:13:52] [Server thread/ERROR]: Parsing error loading built-in advancement minecraft:recipes/food/bread
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:bread'
        at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
        at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
        at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
        at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:203) ~[i$a.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
        at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
        at net.minecraft.advancements.AdvancementManager.func_192777_a(AdvancementManager.java:184) [ns.class:?]
        at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:68) [ns.class:?]
        at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
        at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
[15:13:52] [Server thread/ERROR]: Parsing error loading built-in advancement minecraft:recipes/food/beetroot_soup
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:beetroot_soup'
        at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
        at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
        at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
        at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:203) ~[i$a.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
        at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
        at net.minecraft.advancements.AdvancementManager.func_192777_a(AdvancementManager.java:184) [ns.class:?]
        at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:68) [ns.class:?]
        at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
        at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
[15:13:54] [Server thread/INFO]: Loaded 503 advancements`

Hope you can fix this in a futuire version.

Thanks

**Comment by CosmicHikari** [comment]
Perhaps related to #146 ?

**Comment by MatrexsVigil** [comment]
This is a known issue that will not be fixed.  It happens because I remove and replace the vanilla foods.

**Comment by ProsperCraft** [comment]
Would really love a fix for this, it's alarming to have giant stack trace like this on boot.

**Comment by liach** [comment]
@matrexsvigil you should use registry substitution instead, replacing the old recipe with an empty one, etc.

**Comment by ProsperCraft** [comment]
The other reason this is a problem, is whenever a player changes dims and loads a dim that isn't loaded, the massive stacktrace wall happens, and I have to investigate in case something bad is happening.

Also sometimes advancements stop showing globally to others, and I wonder if this could be related.

**Comment by ProsperCraft** [comment]
Won't fix? ok, we will remove it from our pack, we don't need it anyhow.
