### ISSUE TITLE
[1.10.2] Crash

### ISSUE THREAD

**Issue by SoldierKucha** [MatrexsVigil/harvestcraft#192]
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad$Builder.<init>(UnpackedBakedQuad.java:112)
	at net.minecraftforge.client.model.ItemLayerModel.buildQuad(ItemLayerModel.java:369)
	at net.minecraftforge.client.model.ItemLayerModel.buildSideQuad(ItemLayerModel.java:353)
	at net.minecraftforge.client.model.ItemLayerModel.addSideQuad(ItemLayerModel.java:278)
	at net.minecraftforge.client.model.ItemLayerModel.getQuadsForSprite(ItemLayerModel.java:229)
	at net.minecraftforge.client.model.ItemLayerModel.bake(ItemLayerModel.java:126)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bake(ModelLoader.java:538)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:182)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

**Comment by warlordjones** [comment]
Cannot reproduce, or even confirm that this is a Harvestcraft issue, with just a fragment of a stacktrace.
