### ISSUE TITLE
Worldgen issue with harvestcraft and GregTech (1.10.2)

### ISSUE THREAD

**Issue by GordonHollow** [MatrexsVigil/harvestcraft#202]
Last version of GregTech and PamHarvestCraft

When generate new chunk or world creating with PHC server stopped (don't drop any block, don't see inside any GUI) and console-spammed this: [link](http://pastebin.com/GXhuvLc4) (yeah so long wall just one ERROR)

where major lines is
```
 at com.pam.harvestcraft.blocks.blocks.BlockBaseGarden.func_176196_c(BlockBaseGarden.java:105) ~[BlockBaseGarden.class:?]
	at com.pam.harvestcraft.worldgen.BushWorldWorldGen.generateGarden(BushWorldWorldGen.java:72) ~[BushWorldWorldGen.class:?]
	at com.pam.harvestcraft.worldgen.BushWorldWorldGen.generate(BushWorldWorldGen.java:53) ~[BushWorldWorldGen.class:?]
```

and

```
	at gregtech.common.blocks.GT_Block_GeneratedOres.setOreBlock(GT_Block_GeneratedOres.java:79) ~[GT_Block_GeneratedOres.class:?]
	at gregtech.common.GT_Worldgen_GT_Ore_Layer.executeWorldgen(GT_Worldgen_GT_Ore_Layer.java:84) ~[GT_Worldgen_GT_Ore_Layer.class:?]
	at gregtech.common.GT_Worldgenerator.generateInternal(GT_Worldgenerator.java:69) ~[GT_Worldgenerator.class:?]
	at gregtech.common.GT_Worldgenerator.generate(GT_Worldgenerator.java:46) ~[GT_Worldgenerator.class:?]
```

Without PHC or GregTech all works correctly

**Comment by GordonHollow** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/issues/828

**Comment by nekoexmachina** [comment]
Same happens to me, unfortunatelly.

**Comment by GordonHollow** [comment]
It happen with all people who try using GT and PHC the same time

GT developers says that this strange bug triggered infinity worldgeneration more and more chunks

**Comment by nekoexmachina** [comment]
Yes, just saying that this still happens. Disabling bushes generation from Harvestcraft fixes the issue.

**Comment by GordonHollow** [comment]
For me disable bushes generation in config not work, has the same log with BushWorldGen error

**Comment by GordonHollow** [comment]
HarvestCraft 1.11.2c
-----------------
- World Gen Changes/Fixes for Beehives, Trees, Bushes, and others by mezz

this fix maybe helps, but only 1.11.2
will be this version releases on 1.10.2 later?

**Comment by GordonHollow** [comment]
In new 1.10.2i version - still the same problem
