### ISSUE TITLE
Parsing error loading some built-in food advancements [HarvestCraft 1.12.2t] 

### ISSUE THREAD

**Issue by fandomaniac** [MatrexsVigil/harvestcraft#205]
I'm receiving these errors in the server console:
Server thread/ERROR Parsing error loading built-in advancement minecraft:recipes/food/pumpkin_pie
Server thread/ERROR Parsing error loading built-in advancement minecraft:recipes/food/mushroom_stew
Server thread/ERROR Parsing error loading built-in advancement minecraft:recipes/food/bread
Server thread/ERROR Parsing error loading built-in advancement minecraft:recipes/food/beetroot_soup

I checked with the Forge team and they responded: "something you have installed is removing vanilla recipes which breaks the advancements."

**Here's the full error log from the server console:**
21.04 00:58:11 [Server] Server thread/INFO [FML]: Registry Item: Activating override harvestcraft for minecraft:melon
21.04 00:58:11 [Server] Server thread/INFO [FML]: Registry Item: Activating override harvestcraft for minecraft:beef
21.04 00:58:11 [Server] Server thread/INFO [FML]: Registry Item: Activating override harvestcraft for minecraft:cooked_beef
21.04 00:58:11 [Server] Server thread/INFO [FML]: Registry Item: Activating override malisisdoors for minecraft:jungle_fence_gate
21.04 00:58:11 [Server] Server thread/INFO [FML]: Registry Item: Activating override harvestcraft for minecraft:baked_potato
21.04 00:58:11 [Server] Server thread/INFO [FML]: Registry Item: Activating override malisisdoors for minecraft:dark_oak_door
21.04 00:58:11 [Server] Server thread/INFO [FML]: Registry Item: Activating override malisisdoors for minecraft:fence_gate
21.04 00:58:11 [Server] Server thread/INFO [FML]: Registry Item: Activating override harvestcraft for minecraft:cooked_porkchop
21.04 00:58:11 [Server] Server thread/INFO [FML]: Registry Item: Activating override harvestcraft for minecraft:cooked_chicken
21.04 00:58:11 [Server] Server thread/INFO [FML]: Registry Item: Activating override malisisdoors for minecraft:trapdoor
21.04 00:58:11 [Server] Server thread/INFO [FML]: Registry Item: Activating override harvestcraft for minecraft:porkchop
21.04 00:58:11 [Server] Server thread/INFO [FML]: Registry Item: Activating override malisisdoors for minecraft:acacia_fence_gate
21.04 00:58:11 [Server] Server thread/INFO [FML]: Registry Item: Activating override harvestcraft for minecraft:mushroom_stew
21.04 00:58:11 [Server] Server thread/INFO [FML]: Registry Item: Activating override malisisdoors for minecraft:dark_oak_fence_gate
21.04 00:58:11 [Server] Server thread/INFO [FML]: Registry Item: Activating override harvestcraft for minecraft:cooked_rabbit
21.04 00:58:11 [Server] Server thread/INFO [FML]: Registry Item: Activating override harvestcraft for minecraft:rabbit_stew
21.04 00:58:11 [Server] Server thread/INFO [FML]: Registry Item: Activating override harvestcraft for minecraft:carrot
21.04 00:58:11 [Server] Server thread/INFO [FML]: Registry Item: Activating override harvestcraft for minecraft:cooked_mutton
21.04 00:58:12 [Server] Server thread/INFO [FML]: Applying holder lookups
21.04 00:58:12 [Server] Server thread/INFO [FML]: Holder lookups applied
21.04 00:58:13 [Server] Server thread/INFO [FML]: Loading dimension 0 (world2018) (net.minecraft.server.dedicated.DedicatedServer@4bf597aa)
21.04 00:58:13 [Server] Server thread/ERROR Parsing error loading built-in advancement minecraft:recipes/food/pumpkin_pie
21.04 00:58:13 [Server] INFO com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:pumpkin_pie'
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
21.04 00:58:13 [Server] INFO at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
21.04 00:58:13 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
21.04 00:58:13 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
21.04 00:58:13 [Server] INFO at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:203) ~[i$a.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
21.04 00:58:13 [Server] INFO at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementManager.func_192777_a(AdvancementManager.java:184) [ns.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:68) [ns.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298) [MinecraftServer.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
21.04 00:58:13 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
21.04 00:58:13 [Server] Server thread/ERROR Parsing error loading built-in advancement minecraft:recipes/food/mushroom_stew
21.04 00:58:13 [Server] INFO com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:mushroom_stew'
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
21.04 00:58:13 [Server] INFO at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
21.04 00:58:13 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
21.04 00:58:13 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
21.04 00:58:13 [Server] INFO at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:203) ~[i$a.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
21.04 00:58:13 [Server] INFO at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementManager.func_192777_a(AdvancementManager.java:184) [ns.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:68) [ns.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298) [MinecraftServer.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
21.04 00:58:13 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
21.04 00:58:13 [Server] Server thread/ERROR Parsing error loading built-in advancement minecraft:recipes/food/cookie
21.04 00:58:13 [Server] INFO com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:cookie'
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
21.04 00:58:13 [Server] INFO at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
21.04 00:58:13 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
21.04 00:58:13 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
21.04 00:58:13 [Server] INFO at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:203) ~[i$a.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
21.04 00:58:13 [Server] INFO at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementManager.func_192777_a(AdvancementManager.java:184) [ns.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:68) [ns.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298) [MinecraftServer.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
21.04 00:58:13 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
21.04 00:58:13 [Server] Server thread/ERROR Parsing error loading built-in advancement minecraft:recipes/food/bread
21.04 00:58:13 [Server] INFO com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:bread'
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
21.04 00:58:13 [Server] INFO at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
21.04 00:58:13 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
21.04 00:58:13 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
21.04 00:58:13 [Server] INFO at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:203) ~[i$a.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
21.04 00:58:13 [Server] INFO at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementManager.func_192777_a(AdvancementManager.java:184) [ns.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:68) [ns.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298) [MinecraftServer.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
21.04 00:58:13 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
21.04 00:58:13 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
21.04 00:58:13 [Server] Server thread/ERROR Parsing error loading built-in advancement minecraft:recipes/food/beetroot_soup

**Comment by ghost** [comment]
This is not a bug.

Harvestcraft has only deleted the recipes and items in the inventory and added them to itself.
Does it bother? Simply disable in the harvestcraft.cfg.

**Comment by Roadkill1337** [comment]
This is a problem because it prevents vanilla advancements from being recognized, thus preventing the server from starting up. It simply stops while trying to load advancements from Pam's HarvestCraft. I disabled vanilla recipe changing in the config file (as suggested [here](https://github.com/MatrexsVigil/harvestcraft/issues/54)), but that did not fix the problem. The server is still incapable of parsing the advancements. 

Before you ask, yes, this most absolutely is a problem with Pam's HarvestCraft. I've narrowed it down to this mod. If I remove it from the load list, the server boots up just fine. Is there something I'm missing here? Is there something in the config file that needs to be switched off?

**Comment by Geethebluesky** [comment]
Disabling the vanilla food balance option in the config (I forget its specific name but it's obvious) helps fix some of the advancement issues, but be prepared to see other errors pop up in the log after that.

**Comment by Roadkill1337** [comment]
Even after disabling vanilla recipe changes, the server refuses to start up. It doesn't even crash. It just sits there, which is arguably more frustrating than a crash.

Removing vanilla recipes alters vanilla Minecraft's advancement tree. That was a poor design choice on Pam's part. As a result, this mod is singlehandedly preventing my server from starting. 

Unfortunately, there are no alternatives to HarvestCraft, so I'm stuck with it. Right now, I have my developer working on a hotfix for it, but he's having no success. Pam screwed with a lot of things.

**Comment by clienthax** [comment]
https://github.com/MatrexsVigil/harvestcraft/pull/242

**Comment by Geethebluesky** [comment]
I hope she sees this, but considering inactivity in the repo and the most recent version being 1.12.2u...

**Comment by dooferorg** [comment]
Happening across this because of searching for the same issues. Seems like the mod developer doesn't care about messing things around with the fundamentals within minecraft. Not a good way to go about it IMHO

**Comment by Cyprex** [comment]
This is a common issue with advancements. They break very easily as they fail to load if a recipe they unlock does not exist. This particular issue seems to have been fixed, but in general you can fix this by adding fixed advancent json's into <your world folder>/data/advancements/
Example of such an advancement json: https://github.com/CyclopsMC/IntegratedDynamics/blob/eca39f9dc41c9fda2b0073e4d62ab61e7d516774/src/main/resources/assets/integrateddynamics/advancements/meneglin_basics/menril_production.json
For the original vanilla jsons, my best guess would be checking the vanilla .jar
