### ISSUE TITLE
1.11.2 Missing textures on trees

### ISSUE THREAD

**Issue by EnidanBri** [MatrexsVigil/harvestcraft#214]
I found a tree with obviously fruits on them without a texture. When I tried to harvest the block without texture, the game crashed.

`---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 1/24/17 10:00 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.block.model.BakedQuadRetextured.func_178217_e(BakedQuadRetextured.java:26)
	at net.minecraft.client.renderer.block.model.BakedQuadRetextured.<init>(BakedQuadRetextured.java:17)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.func_188645_a(SourceFile:120)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.<init>(SourceFile:102)
	at net.minecraftforge.client.ForgeHooksClient.getDamageModel(ForgeHooksClient.java:668)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175020_a(BlockRendererDispatcher.java:46)
	at net.minecraft.client.renderer.RenderGlobal.func_174981_a(RenderGlobal.java:1909)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1360)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1246)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1053)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.block.model.BakedQuadRetextured.func_178217_e(BakedQuadRetextured.java:26)
	at net.minecraft.client.renderer.block.model.BakedQuadRetextured.<init>(BakedQuadRetextured.java:17)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.func_188645_a(SourceFile:120)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.<init>(SourceFile:102)
	at net.minecraftforge.client.ForgeHooksClient.getDamageModel(ForgeHooksClient.java:668)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175020_a(BlockRendererDispatcher.java:46)
	at net.minecraft.client.renderer.RenderGlobal.func_174981_a(RenderGlobal.java:1909)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1360)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1246)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['EnidanBri'/179, l='MpServer', x=445.48, y=71.00, z=-526.45]]
	Chunk stats: MultiplayerChunkCache: 557, 557
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-148,64,-52), Chunk: (at 12,4,12 in -10,-4; contains blocks -160,0,-64 to -145,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 106748 game time, 124462 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 55 total; [EntitySheep['Schaf'/103425, l='MpServer', x=482.40, y=69.00, z=-551.80], EntitySheep['Schaf'/103427, l='MpServer', x=484.50, y=69.00, z=-556.50], EntitySheep['Schaf'/103426, l='MpServer', x=485.50, y=69.00, z=-554.50], EntityBat['Fledermaus'/104197, l='MpServer', x=500.72, y=39.98, z=-464.47], EntitySheep['Schaf'/103428, l='MpServer', x=484.50, y=69.00, z=-555.50], EntityBat['Fledermaus'/104231, l='MpServer', x=498.39, y=59.68, z=-486.48], EntityItem['item.tile.torch'/103227, l='MpServer', x=435.30, y=9.00, z=-489.19], EntityItem['item.tile.torch'/103229, l='MpServer', x=438.13, y=14.00, z=-511.55], EntityItem['item.tile.torch'/103228, l='MpServer', x=431.64, y=18.00, z=-502.26], EntitySheep['Schaf'/103231, l='MpServer', x=429.50, y=73.00, z=-526.50], EntitySheep['Schaf'/103230, l='MpServer', x=429.50, y=73.00, z=-527.50], EntitySheep['Schaf'/103233, l='MpServer', x=433.26, y=72.00, z=-519.58], EntitySheep['Schaf'/103232, l='MpServer', x=425.50, y=72.00, z=-521.97], EntityRabbit['Kaninchen'/103235, l='MpServer', x=437.50, y=68.00, z=-464.50], EntityRabbit['Kaninchen'/103234, l='MpServer', x=439.50, y=68.00, z=-465.50], EntityRabbit['Kaninchen'/103236, l='MpServer', x=435.50, y=68.00, z=-463.50], EntityItem['item.tile.torch'/103249, l='MpServer', x=453.14, y=14.00, z=-508.72], EntityMinecartChest['Güterlore'/103251, l='MpServer', x=445.50, y=15.06, z=-452.50], EntityItem['item.tile.torch'/103250, l='MpServer', x=453.88, y=15.00, z=-465.97], EntitySheep['Schaf'/103253, l='MpServer', x=452.50, y=63.00, z=-565.50], EntitySheep['Schaf'/103252, l='MpServer', x=453.50, y=63.00, z=-564.50], EntityBat['Fledermaus'/104020, l='MpServer', x=373.57, y=26.08, z=-546.50], EntitySheep['Schaf'/103255, l='MpServer', x=452.50, y=63.00, z=-566.50], EntityItem['item.tile.torch'/103511, l='MpServer', x=494.50, y=15.00, z=-497.12], EntitySheep['Schaf'/103254, l='MpServer', x=450.50, y=63.00, z=-567.50], EntitySheep['Schaf'/103257, l='MpServer', x=442.50, y=63.00, z=-574.50], EntityItem['item.tile.torch'/103513, l='MpServer', x=490.88, y=19.00, z=-470.24], EntityItem['item.tile.torch'/103512, l='MpServer', x=496.12, y=15.00, z=-497.56], EntitySheep['Schaf'/103259, l='MpServer', x=439.79, y=63.00, z=-575.72], EntitySheep['Schaf'/103258, l='MpServer', x=441.52, y=63.00, z=-575.10], EntityItem['item.tile.torch'/103514, l='MpServer', x=496.13, y=13.00, z=-462.13], EntitySheep['Schaf'/103260, l='MpServer', x=439.80, y=63.00, z=-577.36], EntityBat['Fledermaus'/104032, l='MpServer', x=464.50, y=37.00, z=-448.58], EntityItem['item.tile.rail'/103520, l='MpServer', x=497.16, y=17.00, z=-474.49], EntityBat['Fledermaus'/103780, l='MpServer', x=375.49, y=27.07, z=-543.20], EntitySquid['Tintenfisch'/104045, l='MpServer', x=478.48, y=53.00, z=-515.40], EntitySquid['Tintenfisch'/104044, l='MpServer', x=477.60, y=53.00, z=-514.40], EntitySquid['Tintenfisch'/104049, l='MpServer', x=507.40, y=60.72, z=-541.22], EntitySquid['Tintenfisch'/104048, l='MpServer', x=504.37, y=61.00, z=-537.49], EntityBat['Fledermaus'/104051, l='MpServer', x=413.68, y=23.47, z=-453.50], EntityBat['Fledermaus'/104053, l='MpServer', x=416.21, y=23.03, z=-456.01], EntityBat['Fledermaus'/104052, l='MpServer', x=406.47, y=21.46, z=-452.39], EntityItem['item.tile.torch'/103815, l='MpServer', x=506.69, y=18.00, z=-482.46], EntityItem['item.tile.torch'/103814, l='MpServer', x=507.19, y=18.00, z=-480.38], EntitySquid['Tintenfisch'/104081, l='MpServer', x=479.01, y=54.45, z=-516.49], EntitySquid['Tintenfisch'/104082, l='MpServer', x=476.58, y=53.15, z=-520.57], EntityPlayerSP['EnidanBri'/179, l='MpServer', x=445.48, y=71.00, z=-526.45], EntityMinecartChest['Güterlore'/103865, l='MpServer', x=522.50, y=13.06, z=-489.50], EntityBat['Fledermaus'/104120, l='MpServer', x=503.65, y=20.18, z=-480.75], EntityRabbit['Kaninchen'/103121, l='MpServer', x=400.50, y=64.00, z=-595.50], EntityRabbit['Kaninchen'/103120, l='MpServer', x=400.50, y=64.00, z=-596.50], EntityBat['Fledermaus'/104147, l='MpServer', x=494.63, y=13.72, z=-502.82], EntityBat['Fledermaus'/104171, l='MpServer', x=524.75, y=39.03, z=-450.67], EntityRabbit['Kaninchen'/102386, l='MpServer', x=368.50, y=66.00, z=-462.50], EntityItem['item.tile.torch'/103423, l='MpServer', x=476.41, y=14.00, z=-503.51]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 607630496 bytes (579 MB) / 1471524864 bytes (1403 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.0.2224 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2224.jar) 
	UCHIJAAAA	forge{13.20.0.2224} [Minecraft Forge] (forge-1.11.2-13.20.0.2224.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCHIJAAAA	autosapling{1.11.2-1.3.5} [AutoSapling] (AutoSapling 1.11.2-1.3.5.jar) 
	UCHIJAAAA	hud{1.3.8} [Better HUD] (hud-1.3.8-1.11.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.4.0} [JourneyMap] (journeymap-1.11.2-5.4.0.jar) 
	UCHIJAAAA	harvestcraft{1.11.2a} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2a.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 369.09' Renderer: 'GeForce GTX 560/PCIe/SSE2'
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2224
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 560/PCIe/SSE2 GL version 4.5.0 NVIDIA 369.09, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Ragecraft Faithful 64x64.zip, Ragecraft Faithful - Clear GUI Addon - Clear Glass.zip, Ragecraft Faithful - Clear GUI Addon - Boxes.zip, Ragecraft Faithful - Random Mobs.zip, Ragecraft Faithful - Connected Textures Addon.zip, Ragecraft Faithful - Clear Glass Addon.zip
	Current Language: Deutsch (Deutschland)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD Phenom(tm) II X4 945 Processor`

**Comment by Ramireztime** [comment]
Hey EnidanBri, this issue has been fixed in the latest version of HarvestCraft [available on CurseForge](https://minecraft.curseforge.com/projects/pams-harvestcraft/files/2372766). If any other issues come up using the newer version, please report them. Thanks!
