### ISSUE TITLE
Invalid registration attempt for an Ore Dictionary item

### ISSUE THREAD

**Issue by Insane96** [MatrexsVigil/harvestcraft#218]
```[17:28:55] [main/WARN] [FML]: * Invalid registration attempt for an Ore Dictionary item with name listAllmeatcooked has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[17:28:55] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:654)
[17:28:55] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:640)
[17:28:55] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:638)
[17:28:55] [main/WARN] [FML]: *  at com.pam.harvestcraft.item.GeneralOreRegistry.registerFoodOres(GeneralOreRegistry.java:1396)
[17:28:55] [main/WARN] [FML]: *  at com.pam.harvestcraft.item.GeneralOreRegistry.initOreRegistry(GeneralOreRegistry.java:1082)
[17:28:55] [main/WARN] [FML]: *  at com.pam.harvestcraft.item.ItemRegistry.onItemRegistry(ItemRegistry.java:2538)...```

**Comment by Insane96** [comment]
Full errors list: https://pastebin.com/zhMDVXFC

**Comment by Geethebluesky** [comment]
Getting this as well on forge 2691 and Harvestcraft 1.12.2u.

**Comment by clienthax** [comment]
https://github.com/MatrexsVigil/harvestcraft/pull/241
