### ISSUE TITLE
Shipping Bin message not on server thread

### ISSUE THREAD

**Issue by Kostronor** [MatrexsVigil/harvestcraft#227]
Using the Shipping Bin triggers this warning by Sponge. I guess this is a message event that is not handled in the server thread. Since messages are now executed in a different thread you have to move to the server thread to do modifications of the world.

```
[14:15:48] [Netty Epoll Server IO #22/ERROR] [Sponge]: Detected attempt to add entity 'EntityItem['item.item.emerald'/81201, l='world', x=2762.82, y=60.00, z=-2670.35]' to tracker asynchronously.
 This is very bad as it can cause ConcurrentModificationException's during a server tick.
 Skipping...
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]: java.lang.Exception: Stack trace
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at java.lang.Thread.dumpStack(Thread.java:1333)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at net.minecraft.entity.EntityTracker.handler$onAddEntityToTracker$zda000(EntityTracker.java:576)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:139)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at net.minecraft.world.ServerWorldEventHandler.func_72703_a(ServerWorldEventHandler.java:33)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at net.minecraft.world.World.func_72923_a(World.java:1142)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:1118)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at net.minecraft.world.WorldServer.onSpongeEntityAdded(WorldServer.java:2856)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at net.minecraft.world.WorldServer.forceSpawnEntity(WorldServer.java:2902)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at net.minecraft.world.WorldServer.forceSpawnEntity(WorldServer.java:2885)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at org.spongepowered.common.event.tracking.phase.general.GeneralState.spawnEntityOrCapture(GeneralState.java:83)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at org.spongepowered.common.event.tracking.phase.general.GeneralPhase.spawnEntityOrCapture(GeneralPhase.java:355)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at org.spongepowered.common.event.tracking.CauseTracker.spawnEntity(CauseTracker.java:595)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:2627)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at com.pam.harvestcraft.tileentities.MessageShippingBinBuy.onMessage(MessageShippingBinBuy.java:66)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at com.pam.harvestcraft.tileentities.MessageShippingBinBuy.onMessage(MessageShippingBinBuy.java:12)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at net.minecraftforge.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:56)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at net.minecraftforge.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:36)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:100)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:149)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:51)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.handleServerSideCustomPacket(NetworkDispatcher.java:446)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:269)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:73)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[14:15:54] [Netty Epoll Server IO #22/INFO] [STDERR]: [java.lang.Thread:dumpStack:1333]:        at java.lang.Thread.run(Thread.java:745)
[14:15:54] [Netty Epoll Server IO #22/ERROR] [Sponge]: Detected attempt to add entity 'EntityItem['item.item.emerald'/81220, l='world', x=2762.82, y=60.00, z=-2670.35]' to tracker asynchronously.
```

**Comment by Wissi** [comment]
Awesome mod we love using it on the server. 
Just curious, any update on a fix?

Thanks.

**Comment by Kostronor** [comment]
@MatrexsVigil any news on this?
