### ISSUE TITLE
Tile Entity Errors / Null Pointer Exceptions

### ISSUE THREAD

**Issue by Videonauth** [MatrexsVigil/harvestcraft#258]
Getting this when I place either Apiary, Presser, Ground Trap, Market and Shipping Bin. As well it causes 
the mentioned mods to behave weird (i.e. Textures not loading etc.):
- Refined Storage
- Quark
- Actually Additions

Log Snippet:
---
```
[11:07:15] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1046) [bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraftforge.items.ItemStackHandler.deserializeNBT(ItemStackHandler.java:191) ~[ItemStackHandler.class:?]
	at com.pam.harvestcraft.tileentities.TileEntityPresser.func_145839_a(TileEntityPresser.java:41) ~[TileEntityPresser.class:?]
	at net.minecraft.tileentity.TileEntity.handleUpdateTag(TileEntity.java:333) ~[asc.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147263_a(NetHandlerPlayClient.java:745) ~[bno.class:?]
	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:96) ~[gw.class:?]
	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:18) ~[gw.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
[11:07:15] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1046) [bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraftforge.items.ItemStackHandler.deserializeNBT(ItemStackHandler.java:191) ~[ItemStackHandler.class:?]
	at com.pam.harvestcraft.tileentities.TileEntityApiary.func_145839_a(TileEntityApiary.java:48) ~[TileEntityApiary.class:?]
	at net.minecraft.tileentity.TileEntity.handleUpdateTag(TileEntity.java:333) ~[asc.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147263_a(NetHandlerPlayClient.java:745) ~[bno.class:?]
	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:96) ~[gw.class:?]
	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:18) ~[gw.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
[11:07:15] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1046) [bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraftforge.items.ItemStackHandler.deserializeNBT(ItemStackHandler.java:191) ~[ItemStackHandler.class:?]
	at com.pam.harvestcraft.tileentities.TileEntityMarket.func_145839_a(TileEntityMarket.java:44) ~[TileEntityMarket.class:?]
	at net.minecraft.tileentity.TileEntity.handleUpdateTag(TileEntity.java:333) ~[asc.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147263_a(NetHandlerPlayClient.java:745) ~[bno.class:?]
	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:96) ~[gw.class:?]
	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:18) ~[gw.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
[11:07:18] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3170ms behind, skipping 63 tick(s)
[11:09:08] [Client thread/WARN]: Failed to load texture: quark:textures/blocks/chests/.png
java.io.FileNotFoundException: quark:textures/blocks/chests/.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:69) ~[bzr.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) ~[cae.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SimpleTexture.java:34) ~[byv.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:79) [bza.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:49) [bza.class:?]
	at net.minecraft.client.renderer.tileentity.TileEntitySpecialRenderer.func_147499_a(TileEntitySpecialRenderer.java:64) [bsl.class:?]
	at vazkii.quark.decoration.client.render.RenderTileCustomChest.renderTileEntityAt(RenderTileCustomChest.java:71) [RenderTileCustomChest.class:?]
	at vazkii.quark.decoration.client.render.RenderTileCustomChest.func_180535_a(RenderTileCustomChest.java:26) [RenderTileCustomChest.class:?]
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:172) [bsk.class:?]
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:145) [bsk.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:998) [bqm.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1757) [bqe.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1582) [bqe.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1359) [bqe.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077) [bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[11:09:09] [Client thread/ERROR]: Couldn't load layered image
java.io.FileNotFoundException: minecraft:textures/entity/shield/actuallyadditionsdrill.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:69) ~[bzr.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) ~[cae.class:?]
	at net.minecraft.client.renderer.texture.LayeredColorMaskTexture.func_110551_a(SourceFile:63) [bys.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:79) [bza.class:?]
	at net.minecraft.client.renderer.BannerTextures$Cache.func_187478_a(SourceFile:63) [bqw$a.class:?]
	at net.minecraft.client.renderer.tileentity.TileEntityItemStackRenderer.func_179022_a(TileEntityItemStackRenderer.java:55) [bqc.class:?]
	at noppes.npcs.client.renderer.TileEntityItemStackRendererAlt.func_179022_a(TileEntityItemStackRendererAlt.java:30) [TileEntityItemStackRendererAlt.class:?]
	at elec332.core.client.model.replace.ElecTileEntityItemStackRenderer.func_179022_a(ElecTileEntityItemStackRenderer.java:35) [ElecTileEntityItemStackRenderer.class:?]
	at reborncore.shields.client.RebornItemStackRenderer.func_179022_a(RebornItemStackRenderer.java:57) [RebornItemStackRenderer.class:?]
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:191) [bvh.class:?]
	at net.minecraft.client.renderer.RenderItem.func_184390_a(RenderItem.java:471) [bvh.class:?]
	at net.minecraft.client.renderer.RenderItem.func_175042_a(RenderItem.java:440) [bvh.class:?]
	at com.raoulvdberge.refinedstorage.gui.GuiBase.drawItem(GuiBase.java:241) [GuiBase.class:?]
	at com.raoulvdberge.refinedstorage.gui.grid.stack.GridStackItem.draw(GridStackItem.java:114) [GridStackItem.class:?]
	at com.raoulvdberge.refinedstorage.gui.grid.GuiGrid.drawForeground(GuiGrid.java:445) [GuiGrid.class:?]
	at com.raoulvdberge.refinedstorage.gui.GuiBase.func_146979_b(GuiBase.java:151) [GuiBase.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:118) [big.class:?]
	at com.raoulvdberge.refinedstorage.gui.GuiBase.func_73863_a(GuiBase.java:104) [GuiBase.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) [ForgeHooksClient.class:?]
	at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at Reflector.callVoid(Reflector.java:530) [Reflector.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1425) [bqe.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077) [bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]



```

**Comment by AlgorithmX2** [comment]
The NPE on deserialization appears to be cause of https://github.com/MatrexsVigil/harvestcraft/issues/241 / https://github.com/AlgorithmX2/Chisels-and-Bits/issues/241 as well. Exceptions when loading the chunks causing other tiles to not deserialize properly.

**Comment by Konlii** [comment]
This is because it is not checking `if (compound.getTag("Items") != null)` before trying to deserialize the NBT tag.  I fixed this in my pull request to add persistent inventory to the Apiary.

This fix (plus the changes to add persistent inventory) can be applied to the Presser, Ground Trap, Market, and Shipping Bin as well.

**Comment by searusu** [comment]
sorry to bother you, but it's fixed in 1.11.2h?
i don't really get an overview on github. it's like a mystery to me.
