### ISSUE TITLE
Exception ticking world at ...desertcraft.BlockPamDesertPlant.getDrops

### ISSUE THREAD

**Issue by sealchan1** [MatrexsVigil/harvestcraft#299]
After entering an area in a desert biome Minecraft now crashes with the exception:

Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at java.util.Collections.shuffle(Collections.java:455)
	at java.util.Collections.shuffle(Collections.java:425)
	at com.pam.desertcraft.BlockPamDesertPlant.getDrops(BlockPamDesertPlant.java:130)
	at net.minecraft.block.Block.func_180653_a(Block.java:544)
	at net.minecraft.block.Block.func_176226_b(Block.java:537)
	at net.minecraft.block.BlockBush.func_176475_e(BlockBush.java:65)
	at net.minecraft.block.BlockBush.func_180650_b(BlockBush.java:58)
	at net.minecraft.block.Block.func_180645_a(Block.java:480)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:471)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:220)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

[crash-2017-06-13_07.42.38-server.txt](https://github.com/MatrexsVigil/harvestcraft/files/1071818/crash-2017-06-13_07.42.38-server.txt)

**Comment by sealchan1** [comment]
Severity Level: This issue will force the player to disable Pam's DesertCraft in order to play Minecraft.
