### ISSUE TITLE
Missing cucumber sandwich recipe

### ISSUE THREAD

**Issue by MrTitainin** [MatrexsVigil/harvestcraft#346]
At least JEI shows no recipe for it. 1.12.2zb

**Comment by GamertechAU** [comment]
Second this:

`[16:05:42] [Client thread/ERROR] [FML]: Parsing error loading recipe harvestcraft:cucumbersandwichitem
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 14 column 2 path $.ingredients[2]
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:494) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:708) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:821) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:676) ~[CraftingHelper.class:?]
	at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_211]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:626) [CraftingHelper.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 14 column 2 path $.ingredients[2]
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:476) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[JsonReader.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:730) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:910) ~[TypeAdapters$35$1.class:?]
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]`

**Comment by Pythonic-Rainbow** [comment]
Update.

**Comment by MrTitainin** [comment]
Still an issue in 1.12.2zd. Besides, I actually had 1.12.2zc but on mod list it still shows zb.

**Comment by GamertechAU** [comment]
I'm on zd and getting it. Sorry, missed the OP was on zb

**Comment by SkylineP1g3on** [comment]
https://github.com/MatrexsVigil/harvestcraft/pull/332

This would fix the bad json

**Comment by Pythonic-Rainbow** [comment]
MatrexsVigil seems to ignore PRs. We created several PRs and he just did his own.
