### ISSUE TITLE
1.12.1 c

### ISSUE THREAD

**Issue by Gromyown** [MatrexsVigil/harvestcraft#50]
ok  1.12 c works fine for me    with cooking for blockheads 1.12.1-6.3.6  

so i updated pams 1.12.1 c and i get this error dont get me wronge the server started 

[17:00:35] [Server thread/ERROR]: Parsing error loading built-in advancement minecraft:recipes/food/pumpkin_pie
--
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:pumpkin_pie'
at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(SourceFile:166) ~[l$a.class:?]
at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(SourceFile:150) ~[l$a.class:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:203) ~[i$a.class:?]
at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
at net.minecraft.advancements.AdvancementManager.func_192777_a(AdvancementManager.java:184) [ns.class:?]
at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:68) [ns.class:?]
at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:155) [oo.class:?]
at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[17:00:35] [Server thread/ERROR]: Parsing error loading built-in advancement minecraft:recipes/food/mushroom_stew
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:mushroom_stew'
at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(SourceFile:166) ~[l$a.class:?]
at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(SourceFile:150) ~[l$a.class:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:203) ~[i$a.class:?]
at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
at net.minecraft.advancements.AdvancementManager.func_192777_a(AdvancementManager.java:184) [ns.class:?]
at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:68) [ns.class:?]
at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:155) [oo.class:?]
at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[17:00:35] [Server thread/ERROR]: Parsing error loading built-in advancement minecraft:recipes/food/cookie
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:cookie'
at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(SourceFile:166) ~[l$a.class:?]
at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(SourceFile:150) ~[l$a.class:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:203) ~[i$a.class:?]
at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
at net.minecraft.advancements.AdvancementManager.func_192777_a(AdvancementManager.java:184) [ns.class:?]
at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:68) [ns.class:?]
at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:155) [oo.class:?]
at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[17:00:35] [Server thread/ERROR]: Parsing error loading built-in advancement minecraft:recipes/food/bread
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:bread'
at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(SourceFile:166) ~[l$a.class:?]
at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(SourceFile:150) ~[l$a.class:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:203) ~[i$a.class:?]
at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
at net.minecraft.advancements.AdvancementManager.func_192777_a(AdvancementManager.java:184) [ns.class:?]
at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:68) [ns.class:?]
at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:155) [oo.class:?]
at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[17:00:35] [Server thread/ERROR]: Parsing error loading built-in advancement minecraft:recipes/food/beetroot_soup
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:beetroot_soup'
at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(SourceFile:166) ~[l$a.class:?]
at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(SourceFile:150) ~[l$a.class:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:203) ~[i$a.class:?]
at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
at net.minecraft.advancements.AdvancementManager.func_192777_a(AdvancementManager.java:184) [ns.class:?]
at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:68) [ns.class:?]
at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:155) [oo.class:?]
at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by ghost** [comment]
I am having the same errors pop up in my server, too, running 1.12.1c.

**Comment by xorinzor** [comment]
Same problem here, my logfile is literally > 11.000 lines all with these recipe errors

**Comment by trogarus** [comment]
This is still happening with Harvest-1.12-1.2.6-18 btw.

[latest.log](https://github.com/MatrexsVigil/harvestcraft/files/1564529/latest.log)

**Comment by MatrexsVigil** [comment]
This happens because enableVanillaFoodBalance config is true, replacing the default Minecraft items with my own versions. I can't fix this error spam in the console (to my knowledge).

**Comment by cj89898** [comment]
Okay, so I don't really want to re-open this. But I'm using DW20 1.12.2 pack v1.9.0 and this is my latest.log https://paste.feed-the-beast.com/view/b5b5be20

The setting "enableVanillaFoodBalance" is false in the config, which is why I am commenting and asking about it.

I think this same issue was also re-opened in #205

**Comment by Deathinflames** [comment]
We are still having these spamming the console as well, have enablevanillafoodBalance=false in harvestcraft.cfg but these errors persist.
