### ISSUE TITLE
[1.11.2] Harvestcraft Machines/Traps Causing Issues

### ISSUE THREAD

**Issue by Mace134** [MatrexsVigil/harvestcraft#55]
I realize that you may have moved on to 1.12.XX development but the issue that you resolved in your 1.12.1b release is still an issue in the latest 1.11.2h release. I was really hoping that you might go back and apply the fix if it's not too much trouble.

> [15:11:38] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1046) [bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraftforge.items.ItemStackHandler.deserializeNBT(ItemStackHandler.java:191) ~[ItemStackHandler.class:?]
	at com.pam.harvestcraft.tileentities.TileEntityPresser.func_145839_a(TileEntityPresser.java:41) ~[TileEntityPresser.class:?]
	at net.minecraft.tileentity.TileEntity.handleUpdateTag(TileEntity.java:331) ~[asc.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147263_a(NetHandlerPlayClient.java:745) ~[bno.class:?]
	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:96) ~[gw.class:?]
	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:18) ~[gw.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more

[Harvestcraft_Block_NullPointer.log](https://github.com/MatrexsVigil/harvestcraft/files/1331871/Harvestcraft_Block_NullPointer.log)

**Comment by KorDum** [comment]
Please fix it.

**Comment by HalsabSneider** [comment]
Hi,
it would be very, very, veeeery nice if you can do a backport of this fix for 1.11.2 :)
Thanks!

**Comment by MatrexsVigil** [comment]
Not accepting non 1.12.2 bug reports at this time.
