### ISSUE TITLE
Error With NEI Which Can Cause Crashes With Certain Other Mods

### ISSUE THREAD

**Issue by Haldrie** [MatrexsVigil/harvestcraft#56]
I'm working on a modpack using MultiMC to view the log while the game loads to see errors and I found one that I narrowed down to your mod, Harvestcraft, when working with NEI. To verify I loaded minecraft with only Forge 10.13.4.1614,  NEI 1.0.5.120, CodeChickenCore 1.0.7.47 and Harvestcraft 1.7.10Lb. The following is the full log from loading the flat world I created to test this. The error at the end is what happens when I press U over an item to view it's uses in recipes in NEI and while it seems to work in game that error shows up in the log window and it only happens with Harvestcraft. When combined with another mod I'm putting in my pack this also leads to the game crashing.

MultiMC version: 0.4.7

Minecraft folder is:
C:/Games/Minecraft/MultiMC/instances/Mod Testing/minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_66/bin/javaw.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx2048m, -Duser.language=en, -jar, C:/Games/Minecraft/MultiMC/jars/NewLaunch.jar]

Minecraft process ID: 6452

Using onesix launcher.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Games/Minecraft/MultiMC/instances/Mod Testing/natives

Traits:
  []

Libraries:
  C:/Games/Minecraft/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
  C:/Games/Minecraft/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Games/Minecraft/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Games/Minecraft/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Games/Minecraft/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Games/Minecraft/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Games/Minecraft/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Games/Minecraft/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Games/Minecraft/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Games/Minecraft/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Games/Minecraft/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Games/Minecraft/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Games/Minecraft/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Games/Minecraft/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Games/Minecraft/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Games/Minecraft/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Games/Minecraft/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Games/Minecraft/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Games/Minecraft/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Games/Minecraft/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Games/Minecraft/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Games/Minecraft/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Games/Minecraft/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Games/Minecraft/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Games/Minecraft/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Games/Minecraft/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Games/Minecraft/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Games/Minecraft/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Games/Minecraft/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Games/Minecraft/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Games/Minecraft/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Games/Minecraft/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Games/Minecraft/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Games/Minecraft/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Games/Minecraft/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Games/Minecraft/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Games/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Games/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Games/Minecraft/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Games/Minecraft/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Games/Minecraft/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Games/Minecraft/MultiMC/versions/1.7.10/1.7.10.jar

Mods:
  CodeChickenCore-1.7.10-1.0.7.47-universal
  NotEnoughItems-1.7.10-1.0.5.120-universal
  Pam's HarvestCraft 1.7.10Lb

Params:
  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, C:/Games/Minecraft/MultiMC/instances/Mod Testing/minecraft, --assetsDir, C:/Games/Minecraft/MultiMC/assets, --assetIndex, 1.7.10, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {"twitch_access_token":["<TWITCH_ACCESS_TOKEN>"]}, --userType, mojang, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker]

Window size: 854 x 480

Preparing native libraries...
Extracting twitch-platform-5.16-natives-windows-64.jar
Extracting twitch-external-platform-4.5-natives-windows-64.jar
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar

[21:48:18] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[21:48:18] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[21:48:18] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[21:48:18] [main/INFO] [FML]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[21:48:18] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_66, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_66
[21:48:18] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:48:18] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:48:18] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:48:18] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[21:48:18] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:48:18] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:48:18] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:48:19] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[21:48:19] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[21:48:19] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:48:19] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:48:20] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:48:20] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:48:20] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[21:48:20] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[21:48:20] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[21:48:20] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[21:48:21] [main/INFO]: Setting user: <PROFILE NAME>
[21:48:22] [Client thread/INFO]: LWJGL Version: 2.9.1
[21:48:23] [Client thread/INFO] [STDOUT]: [cpw.mods.fml.client.SplashProgress:start:188]: ---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 1/8/16 9:48 PM
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 378452432 bytes (360 MB) / 649592832 bytes (619 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2048m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 361.43' Renderer: 'GeForce GTX 550 Ti/PCIe/SSE2'
[21:48:23] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[21:48:23] [Client thread/INFO] [FML]: MinecraftForge v10.13.4.1614 Initialized
[21:48:23] [Client thread/INFO] [FML]: Replaced 183 ore recipies
[21:48:24] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[21:48:24] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[21:48:24] [Client thread/INFO] [FML]: Searching C:\Games\Minecraft\MultiMC\instances\Mod Testing\minecraft\mods for mods
[21:48:24] [Client thread/INFO] [FML]: Also searching C:\Games\Minecraft\MultiMC\instances\Mod Testing\minecraft\mods\1.7.10 for mods
[21:48:30] [Client thread/INFO] [FML]: Forge Mod Loader has identified 6 mods to load
[21:48:30] [Client thread/INFO] [FML]: FML has found a non-mod file CodeChickenLib-1.7.10-1.1.3.138-universal.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[21:48:31] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, CodeChickenCore, NotEnoughItems, harvestcraft] at CLIENT
[21:48:31] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, CodeChickenCore, NotEnoughItems, harvestcraft] at SERVER
[21:48:31] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:Pam's HarvestCraft
[21:48:31] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[21:48:31] [Client thread/INFO] [FML]: Found 341 ObjectHolder annotations
[21:48:31] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[21:48:31] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[21:48:31] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[21:48:31] [Client thread/INFO] [FML]: Applying holder lookups
[21:48:31] [Client thread/INFO] [FML]: Holder lookups applied
[21:48:31] [Client thread/INFO] [FML]: Injecting itemstacks
[21:48:31] [Client thread/INFO] [FML]: Itemstack injection complete
[21:48:31] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[21:48:31] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[21:48:32] [Thread-9/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[21:48:32] [Thread-9/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[21:48:32] [Thread-9/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[21:48:32] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[21:48:32] [Sound Library Loader/INFO]: Sound engine started
[21:48:32] [Client thread/INFO]: Created: 16x16 textures/blocks-atlas
[21:48:32] [Client thread/INFO]: Created: 16x16 textures/items-atlas
[21:48:32] [Client thread/ERROR] [CodeChickenCore]: Unable to do mod description scrolling due to lack of stencil buffer
[21:48:32] [Client thread/ERROR] [CodeChickenCore]: Unable to do mod description scrolling due to lack of stencil buffer
[21:48:32] [Client thread/INFO] [FML]: Injecting itemstacks
[21:48:32] [Client thread/INFO] [FML]: Itemstack injection complete
[21:48:32] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 6 mods
[21:48:32] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:Pam's HarvestCraft
[21:48:33] [Client thread/INFO]: Created: 512x512 textures/blocks-atlas
[21:48:34] [Client thread/INFO]: Created: 512x512 textures/items-atlas
[21:48:34] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[21:48:34] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: SoundSystem shutting down...
[21:48:34] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     Author: Paul Lamb, www.paulscode.com
[21:48:34] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[21:48:34] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[21:48:34] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[21:48:34] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[21:48:34] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[21:48:34] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[21:48:34] [Client thread/ERROR] [TEXTURE ERRORS]: +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
[21:48:34] [Client thread/ERROR] [TEXTURE ERRORS]: The following texture errors were found.
[21:48:34] [Client thread/ERROR] [TEXTURE ERRORS]: ==================================================
[21:48:34] [Client thread/ERROR] [TEXTURE ERRORS]:   DOMAIN harvestcraft
[21:48:34] [Client thread/ERROR] [TEXTURE ERRORS]: --------------------------------------------------
[21:48:34] [Client thread/ERROR] [TEXTURE ERRORS]:   domain harvestcraft is missing 1 texture
[21:48:34] [Client thread/ERROR] [TEXTURE ERRORS]:     domain harvestcraft has 1 location:
[21:48:34] [Client thread/ERROR] [TEXTURE ERRORS]:       mod harvestcraft resources at C:\Games\Minecraft\MultiMC\instances\Mod Testing\minecraft\mods\Pam's HarvestCraft 1.7.10Lb.jar
[21:48:34] [Client thread/ERROR] [TEXTURE ERRORS]: -------------------------
[21:48:34] [Client thread/ERROR] [TEXTURE ERRORS]:     The missing resources for domain harvestcraft are:
[21:48:34] [Client thread/ERROR] [TEXTURE ERRORS]:       textures/items/chocolaterollItem.png
[21:48:34] [Client thread/ERROR] [TEXTURE ERRORS]: -------------------------
[21:48:34] [Client thread/ERROR] [TEXTURE ERRORS]:     No other errors exist for domain harvestcraft
[21:48:34] [Client thread/ERROR] [TEXTURE ERRORS]: ==================================================
[21:48:34] [Client thread/ERROR] [TEXTURE ERRORS]: +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
[21:48:34] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[21:48:34] [Sound Library Loader/INFO]: Sound engine started
[21:48:55] [Server thread/INFO]: Starting integrated minecraft server version 1.7.10
[21:48:55] [Server thread/INFO]: Generating keypair
[21:48:55] [Server thread/INFO] [fml.ModTracker]: This world was saved with mod NotEnoughItems version 1.0.5.118 and it is now at version 1.0.5.120, things may not work well
[21:48:55] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
[21:48:55] [Server thread/INFO] [FML]: Applying holder lookups
[21:48:55] [Server thread/INFO] [FML]: Holder lookups applied
[21:48:55] [Server thread/INFO] [FML]: Loading dimension 0 (Flat Test World) (net.minecraft.server.integrated.IntegratedServer@5fae4db8)
[21:48:55] [Server thread/INFO] [FML]: Loading dimension 1 (Flat Test World) (net.minecraft.server.integrated.IntegratedServer@5fae4db8)
[21:48:55] [Server thread/INFO] [FML]: Loading dimension -1 (Flat Test World) (net.minecraft.server.integrated.IntegratedServer@5fae4db8)
[21:48:55] [Server thread/INFO]: Preparing start region for level 0
[21:48:56] [Server thread/INFO]: Changing view distance to 12, from 10
[21:48:56] [Netty Client IO #0/INFO] [FML]: Server protocol version 2
[21:48:56] [Netty IO #1/INFO] [FML]: Client protocol version 2
[21:48:56] [Netty IO #1/INFO] [FML]: Client attempting to join with 6 mods : CodeChickenCore@1.0.7.47,NotEnoughItems@1.0.5.120,FML@7.10.99.99,harvestcraft@1.7.10j,Forge@10.13.4.1614,mcp@9.05
[21:48:56] [Netty IO #1/INFO] [FML]: Attempting connection with missing mods [] at CLIENT
[21:48:56] [Netty Client IO #0/INFO] [FML]: Attempting connection with missing mods [] at SERVER
[21:48:56] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[21:48:56] [Client thread/INFO] [FML]: [Client thread] Client side modded connection established
[21:48:56] [Server thread/INFO]: <PROFILE NAME>[local:E:34a6d22d] logged in with entity id 270 at (688.9677540722947, 4.0, 555.5141163161024)
[21:48:56] [Server thread/INFO]: <PROFILE NAME> joined the game
[21:49:04] [Client thread/ERROR] [NotEnoughItems]: Error loading recipe: 
java.lang.ArrayIndexOutOfBoundsException: 9
	at codechicken.nei.recipe.ShapelessRecipeHandler$CachedShapelessRecipe.setIngredients(ShapelessRecipeHandler.java:53) ~[ShapelessRecipeHandler$CachedShapelessRecipe.class:?]
	at codechicken.nei.recipe.ShapelessRecipeHandler$CachedShapelessRecipe.<init>(ShapelessRecipeHandler.java:47) ~[ShapelessRecipeHandler$CachedShapelessRecipe.class:?]
	at codechicken.nei.recipe.ShapelessRecipeHandler.forgeShapelessRecipe(ShapelessRecipeHandler.java:160) [ShapelessRecipeHandler.class:?]
	at codechicken.nei.recipe.ShapelessRecipeHandler.loadUsageRecipes(ShapelessRecipeHandler.java:129) [ShapelessRecipeHandler.class:?]
	at codechicken.nei.recipe.TemplateRecipeHandler.loadUsageRecipes(TemplateRecipeHandler.java:350) [TemplateRecipeHandler.class:?]
	at codechicken.nei.recipe.TemplateRecipeHandler.getUsageHandler(TemplateRecipeHandler.java:472) [TemplateRecipeHandler.class:?]
	at codechicken.nei.recipe.GuiUsageRecipe.openRecipeGui(GuiUsageRecipe.java:20) [GuiUsageRecipe.class:?]
	at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:20) [RecipeItemInputHandler.class:?]
	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307) [GuiContainerManager.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java) [bex.class:?]
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73869_a(GuiContainerCreative.java:301) [bfl.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java) [bex.class:?]
	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java) [GuiContainerManager.class:?]
	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:475) [GuiContainerManager.class:?]
	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:465) [GuiContainerManager.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java) [bex.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276) [bdw.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]

**Comment by Haldrie** [comment]
Quick little update I decided to test this out with 1.7.10k and this error does not occur with that version.

**Comment by b0bst3r** [comment]
Why did you close this without fixing it, if it wasn't for this github I would never have found out what is spamming the console so bad with this error.

Occurs in every version after 1.7.10k upto Pams HarvestCraft 1.7.10Lb.jar

**Comment by Syndaryl** [comment]
1.7.10 is not supported.

**Comment by b0bst3r** [comment]
Lol look at the dates, back then it was :p
